name: CI
run-name: MMM CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pipenv
      - run: pipenv install --system --dev
      - run: bin/build
      - uses: actions/upload-artifact@v4
        with:
          name: mega-money-millions_${{ github.sha }}
          path: dist/mega_money_millions-*.tar.gz
